config/routes.rb
Rails.application.routes.draw do

  get 'songs/index'

  root 'songs#index'
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :users, only: [ :new, :create, :update, :edit, :show ] do

  end
  resources :songs do
    
  end
  get 'login', to: 'sessions#new', as: :login
  get 'signup', to: 'users#new', as: :signup
  delete 'logout', to: 'sessions#destroy', as: :logout

  get 'language', to: 'users#language', as: :set_locale

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user
  scope :hot_songs, -> { joins(:likeships).
                                       group('songs.id').
                                       order('count(likeships.id) desc').
                                       limit(10) }
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader
  has_many :songs, dependent: :delete_all
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  VALID_EMAIL_REGEX =/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  VALID_NAME_REGEX = /\A[A-Za-z][A-Za-z0-9._-]{2,19}\z/
  validates :name, presence: true,
                            length: { maximum: 50 },
                            format: { with: VALID_NAME_REGEX },
                            uniqueness: { case_sensitive: false }
  validates :email, presence: true,
                            format: { with: VALID_EMAIL_REGEX },
                            uniqueness: { case_sensitive: true }
  validates :password, presence: true,
                                  confirmation: true,
                                  length: { in: 6..16 },
                                  on: :create
  validates :bio, length: { maximum: 140 }

  #Find user by name
  def to_param
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include UsersHelper
  before_action :set_locale

  private

  def set_locale
    I18n.locale = current_user.try(:locale) || I18n.default_locale
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :not_login_user, only: [ :new ]

  def new
    @user = User.new
    render layout: "users_form"
  end

  def create
    if @user = login(params[:session][:email], params[:session][:password], params[:session][:remember])
      flash[:success] = "#{t('.successfully')}"
      respond_to do |format|
        format.html { redirect_back_or_to root_path }
        format.js
      end
    else
      user = User.find_by_email(params[:session][:email])
      if user
        flash.now[:warning] = "sessions.new.inactivation"
        @inactivation = true
      else
        flash.now[:error] = "#{t('sessions.new.invalid_email_password_combination')}"
      end
      respond_to do |format|
        format.html { render action: 'new' }
        format.js
      end
    end
  end

  def destroy
    logout
    redirect_to root_path
    flash[:success] = "#{t('.successfully')}"
  end

  private

    def not_login_user
      if logged_in?
        redirect_to root_path
        flash[:warning] = "#{t('users.has_already_logged_in')}"
      end
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.includes(:user).all.order("created_at desc").page params[:page]
    @hot_songs = Song.hot_songs
    @user_panel = true
  end

  def show
    @song = Song.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [ :edit, :update ]
  before_action :find_correct_user, only: [ :edit, :update ]
  before_action :find_user, only: [ :show ]

  def new
    @user = User.new
    @signup = true
    render layout: "users_form"
  end

  def show
    if @user
      @songs = @user.songs.order("created_at desc")
    else
      redirect_to root_path
      flash[:error] = "#{t('.no_user')}"
    end
  end

  def create
    @user = User.new(user_params)
    debugger
    if @user.save
      flash[:success] = "#{t('.successfully')}"
      respond_to do |format|
          format.html { redirect_to root_path }
          format.js
      end
    else
      respond_to do |format|
        format.html { render 'new' }
        format.js
      end
    end
  end

  def edit
  end

  def update
    debugger
    if @user.update_attributes(update_user_params)
      flash[:success] = "#{t('.successfully')}"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash.now[:error] = "#{t('.faild')}"
      respond_to do |format|
        format.html { render 'edit' }
        format.js
      end
    end
  end

  private

    def find_correct_user
      @user = User.find_by_name(params[:id])
      unless current_user?(@user)
        flash[:warning] = "#{t('permission_denied')}"
        redirect_to root_path
      end
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def find_user
      @user = User.find_by_name(params[:id])
    end

    def not_login_user
      if logged_in?
        redirect_to root_path
        flash[:warning] = "#{t('users.has_already_logged_in')}"
      end
    end

    def update_user_params
      params.require(:user).permit(:bio, :avator, :locale, :password, :password_confirmation)
    end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
end

app/views/layouts/_navbar.html.slim
- if logged_in?
  = render 'users/user_panel'
- else
  .ui.grid.form.basic.segment
    #full-button.ui.buttons.sixteen.wide.column
      = link_to "#{t('users.signup')}", :signup, class: "ui blue inverted button"
      .or
      = link_to "#{t('users.login')}", :login, class: "ui purple inverted button"
  .ui.red.inverted.center.aligned.segment
    #site-status
      = link_to "中文简体", set_locale_url(locale: "zh-CN"), class: "ui red label"
      = link_to "English", set_locale_url(locale: "en"), class: "ui red label"
      .ui.divider
      .site-params
        p #{t('.total_users')}: #{t('users.show.users_count', count: User.count)}
        p #{t('users.show.total_songs')}: #{t('users.show.songs_count', count: Song.count)}
        

app/views/layouts/application.html.erb
doctype html
html
  head
    title Ting
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
  body
    .ui.fixed.green.inverted.menu.center.aligned.segment
      = link_to root_path, id: "logo", class: "item"
        i.music.icon
    = render 'shared/flash'
    .container.animated.fadeIn
      - if @user_panel
        .ui.grid
          .two.wide.column
          #main.nine.wide.column
            = yield
            .right.ui.rail
              .ui.sticky
                = render 'layouts/navbar'
      - else
        = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title Ting
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
  body
    .ui.fixed.green.inverted.menu.center.aligned.segment
      = link_to root_path, id: "logo", class: "item"
        i.music.icon
    = render 'shared/flash'
    .container.animated.fadeIn
      - if @user_panel
        .ui.grid
          .two.wide.column
          #main.nine.wide.column
            = yield
            .right.ui.rail
              .ui.sticky
                = render 'layouts/navbar'
      - else
        = yield

app/views/layouts/users_form.html.slim
doctype html
html
  head
    title Ting
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body

    .pin-button
      = link_to "#{t('.home')}", songs_path, class: "ui blue inverted pull-right button"
      - if @signup
        = link_to "#{t('users.login')}", :login, class: "ui green inverted pull-right button"
      - else
        = link_to "#{t('users.signup')}", :signup, class: "ui green inverted pull-right button"
    img#rainyday src="#{asset_path("night.jpg")}"
    .wallpaper
      = yield

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    .ui.error.message
      i.close.icon
      .header
        | #{t('.the_form_contains')}
        - if I18n.locale.to_s == "zh-CN"
          = object.errors.count
          |  个错误
        - else
          = pluralize(object.errors.count, "error")
      ul.list
        - object.errors.full_messages.each do |msg|
          li = msg

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div id="t-flash" class="ui <%= key %> message flash center aligned segment">
  	  <%= value %>
  </div>
<% end %>
<script>
  $(function(){
    setTimeout(function(){
      $(".ui.flash").closest(".message").addClass('animated fadeOutUp')
                                                        .one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',
      function(){
        $('#t-flash').remove();
      });
    },3000)
  })
</script>

app/views/songs/_form.html.slim
= form_for song, remote: true do |f|
  #song-errors
    = render 'shared/error_messages', object: song
  .ui.form
    .fields
      .eight.wide.field
        .ui.labeled.input
          .ui.teal.label http://www.xiami.com/song/
          - if action_name == "edit"
            = f.text_field :s_id, placeholder: "#{t('activerecord.attributes.song.s_id')}", disabled: "disabled"
          - else
            = f.text_field :s_id, placeholder: "#{t('activerecord.attributes.song.s_id')}"
      .four.wide.field
        = f.text_field :title, placeholder: "#{t('.title')}", disabled: "disabled"
      .four.wide.field
        = f.text_field :artist, placeholder: "#{t('.singer')}", disabled: "disabled"
    .field
      = f.text_area :content, placeholder: "#{t('.content')}"
      = f.hidden_field :pic
    = f.submit "#{t('form.submit')}", class: "ui submit button orange right floated", data: { disable_with: "#{t('form.submitting')}" }
    span.pull-right.help-inline Ctrl+Enter
javascript:
  if($('input#song_title').val().length > 0){
    title = $('input#song_title').val().replace(/&#039;/,"'")
    $('input#song_title').val(title)
    }
#xiami-errors data-blank="#{t('activerecord.attributes.song.s_id')} #{t('.cant_be_blank')}" data-cant_fetch="#{t('songs.cant_fetch')}" data-passed="#{t('.passed')}"

app/views/songs/_play_list.html.slim
p.share-button
  a href="http://service.weibo.com/share/share.php?url=#{song_url(@song)}&type=3&pic=#{song.pic}&title=#{song.title}" target="_blank"
    i.weibo.red.icon
  

app/views/songs/_share_buttons.html.slim
p.share-button
  a href="http://service.weibo.com/share/share.php?url=#{song_url(@song)}&type=3&pic=#{song.pic}&title=#{song.title}" target="_blank"
    i.weibo.red.icon
  a href="https://twitter.com/intent/tweet?url=#{song_url(song)}&text=#{song.title}&via=Ting"  target="_blank"
    i.twitter.blue.icon
  a href="http://www.facebook.com/sharer.php?u=#{song_url(song)}"  target="_blank"
    i.facebook.purple.icon

app/views/songs/_song.html.slim
- cache [song, index] do
  section.ui.two.column.grid.segment.stacked.songs-list id="song-#{song.id}"
    .five.wide.column
      - unless index
        .ui.left.red.corner.label
          i.heart.icon
      .album-pic
        .outer-pic.ui.circular.image
          img src="#{song.pic}"
        a data-xiami_id="#{song.s_id}" class="ui corner label playBtn"
          i.play.icon
    .eleven.wide.column.song-info
      - if current_user == song.user
        .operate
          = link_to edit_song_path(song), class: "edit-song" do
            i.green.pencil.icon
          = link_to song_path(song), data: { method: "delete", confirm: "#{t('form.are_you_sure')}", remote: true } do
            i.red.trash.icon
      .ui.right
        h3.header
          i.orange.sound.icon
          = link_to song.title.html_safe, song
        .singer
          | #{t('activerecord.attributes.song.artist')}:
          a = song.artist
        .song-content
          = parse_text(song.content)
      .song-footer
        .com-count
          - author = song_url(song) + "#comments"
          = link_to author do
            i.green.comment.icon
            = song.comments.size
        .musician
          = image_tag(song.user.avatar_url(:thumb), class: "ui avatar image")
          = link_to song.user.name, song.user

app/views/songs/_songs.html.slim
- cache [:songs, @songs] do
  - if index
    - if logged_in?
      - class_name = "modal-en" unless I18n.locale.to_s == "zh-CN"
      .ui.green.button.modal-toggle class="#{class_name}" =t('.share_a_song')
      .ui.modal.song-form
        i.close.red.icon
        .content
          = render 'songs/form', song: current_user.songs.new

  #songs data-image="#{asset_path("loading.gif")}"
    - for song in @songs
      = render 'song', song: song, index: index
    #pagination data-loaded="#{t('.loaded')}"
      = paginate @songs

  audio id="player" data-xiami_id="-1"

app/views/songs/create.js.erb
<% if @song.errors.empty? %>
    new_song = "<%= j render 'song', song: @song, index: true %>";
    $('#songs').prepend(new_song);
    animated();
<% else %>
  $('#song-errors').html("<%= j render 'shared/error_messages', object: @song %>");
  $('#error_explanation').transition('tada');
<% end %>
$('.ui.form').removeClass('loading')
$('.ui.form .button').removeClass('disabled')

function animated() {
  $('#error_explanation').html("");
  $('#song-<%= @song.id %>').addClass('animated flipInX');
  $('#new_song').trigger('reset');  
  $('.close.red').click();
}

app/views/songs/index.html.slim
= render 'songs', index: true

app/views/songs/show.html.slim
- id = @song.s_id
- user = @song.user
- cache @song do
  .ui.grid
    .four.wide.column
    .eight.wide.column
      .ui.one.column.grid.songs-list id="song-#{@song.id}"
        .sixteen.wide.column.song-info

          .song-container.ui.grid
            .ui.five.wide.column
              .album-pic
                .outer-pic.ui.circular.image.dimmer-image
                  .ui.dimmer
                    .content
                      .center
                        a.playBtn data-xiami_id="#{@song.s_id}"
                          i.ui.red.huge.play.icon
                  img src="#{@song.pic}"

            .ui.eleven.wide.column
              .song-panel
                h3.header
                  i.orange.sound.icon
                  = link_to @song.title.html_safe, @song
                p
                  i.user.green.icon
                  a = @song.artist
                p.song-toolbar
                  = link_to user
                    = image_tag(@song.user.avatar_url(:small), class: "ui mini-avatar avatar image run-popup", data: { content: "#{user.name}", position: "bottom center" } )
                  span.song-tools-divider •

                  i.teal.calendar.icon
                  = @song.created_at.strftime("%F")
                  span.song-tools-divider •

                  span.item id="like-song-#{@song.id}"
                    - @likeable = Likeship.likeable(@song)
                    = likeable_likes_tag @likeable

                  - if current_user == user
                    span.song-tools-divider •
                    = link_to edit_song_path(@song) do
                      i.green.icon.pencil
                    span.song-tools-divider •

                    = link_to song_path(@song), method: :delete, data: { confirm: "#{t('form.are_you_sure')}" }
                      i.red.icon.trash
                = render 'share_buttons', song: @song

            .ui.sixteen.wide.column
              .song-content
                = parse_text(@song.content)
          .song-footer

      .ui.horizontal.icon.divider
        i.circular.red.chat.icon

      #comments
        .column
          .ui.comments
            - if @comments.any?
              = render @comments
            - else
              .ui.center.aligned.basic.segment =t('comments.no_comments_yet')

          = paginate @comments

          .ui.horizontal.icon.divider
            i.circular.green.pencil.icon
          - if logged_in?
            = render 'comments/form'
          - else
            .ui.center.aligned.basic.segment
              = link_to :login
                .ui.animated.fade.blue.button
                  .visible.content =t('users.login_first')
                  .hidden.content =t('users.login')
  audio id="player" data-xiami_id="-1"

app/views/users/_user_panel.html.slim
.ui.large.vertical.labeld.menu
  .ui.header.item.center.teal.label
    
  = link_to edit_user_path(current_user), class: "item"
    i.settings.blue.icon
    | #{t('.settings')}
  = link_to :logout, method: :delete, class: "item"
    i.sign.out.red.icon
    | #{t('users.logout')}

app/views/users/create.js.erb
$('.ui.form').removeClass('loading')
<% if @user.errors.empty? %>
  Turbolinks.visit('<%= root_path %>');
<% else %>
  $('#signup-errors').html("<%= j render 'shared/error_messages', object: @user %>");
  $('#error_explanation').transition('tada');
<% end %>

app/views/users/edit.html.slim
.ui.grid
  .six.wide.column
  .four.wide.column
    .ui.form
      #user-edit-errors
        = render 'shared/error_messages', object: @user
      = form_for @user, remote: true do |f|
        .ui.center.aligned.field.basic.segment
          = image_tag(current_user.avatar_url(:large), class: "ui image circular thumb user-avatar user-avatar-upload run-popup", data: { content: "#{t('.upload_avatar')}", position: "top center" })
          = f.file_field :avatar, class: "upload-avatar"
        .inline.fields.ui.center.aligned.basic.segment
          - I18n.available_locales.each do |locale|
            .field
              .ui.radio.checkbox.checked
                = f.radio_button(:locale, "#{locale}")
                = f.label t("locales.#{locale}")
        .field
          = f.text_field :email, placeholder: "#{t('activerecord.attributes.user.email')}", disabled: "disabled"
        .field
          = f.text_field :bio, placeholder: "#{t('activerecord.attributes.user.bio')}"
        .ui.buttons.session-buttons
          = link_to "#{t('.my_page')}", user_path(@user), class: "ui button orange"
          .or
          = f.submit "#{t('form.save')}", class: "ui blue button"

app/views/users/new.html.slim
.signup-form
  #signup-errors
    = render 'shared/error_messages', object: @user
  = form_for @user, remote: true do |f|
    .ui.form
      .field
        .ui.left.icon.large.input
           = f.text_field :name, placeholder: "#{t('activerecord.attributes.user.name')}"
           i.user.icon
      .field
        .ui.left.icon.large.input
           = f.text_field :email, placeholder: "#{t('activerecord.attributes.user.email')}"
           i.mail.icon
      .field
        .ui.left.icon.large.input
           = f.password_field :password, placeholder: "#{t('activerecord.attributes.user.password')}"
           i.lock.icon
      .field
        .ui.left.icon.large.input
           = f.password_field :password_confirmation, placeholder: "#{t('activerecord.attributes.user.password_confirmation')}"
           i.lock.icon
      = f.submit "#{t('users.signup')}", class: "ui fluid green large button", data: { disable_with: "#{t('form.submitting')}" }

app/views/users/show.html.slim
#canvas-bg
canvas#particles
.ui.grid
  .three.wide.column
  .ten.wide.column
    #user-show.ui.grid
      .one.wide.column
      .fourteen.wide.column
        .ui.grid
          .one.wide.column
          .ui.five.wide.column.center.aligned.info-column
            = image_tag(@user.avatar_url(:large), class: "ui image circular lg  run-popup")
            .center
              h3 = @user.name
            .center.bio
              = @user.bio
            .ui.divider
            - class_name = "ui left aligned basic segment" unless I18n.locale.to_s == "zh-CN"
            .user-status class="#{class_name}"
              .user-created-at
                p #{t('.created_at')}: #{time_ago_in_words(@user.created_at)} #{t('.ago')}
              .user-songs-count
                p #{t('.total_songs')}: #{t('.songs_count', count: @user.songs.count)}

          .nine.wide.column.content-column
              .ui.secondary.large.menu data-loading="#{t('.loading')}"



              .status-panel
                

audio id="player" data-xiami_id="-1"

javascript:
  $(function() {
    if($("#particles").size()>0){
      (function() {
        var width, height, largeHeader, canvas, ctx, circles, target, animateHeader = true;
        width = $('#canvas-bg').width();
        height= $('#canvas-bg').height();
        target = {x: 0, y: height};
        largeHeader = document.getElementById('canvas-bg');
        largeHeader.style.height = height+'px';
        canvas = document.getElementById('particles');
        canvas.width = width;
        canvas.height = height;
        ctx = canvas.getContext('2d');

        circles = [];
        for(var x = 0; x < width*0.5; x++) {
          var c = new Circle();
          circles.push(c);
        }
        animate();
          window.addEventListener('resize',function(){
          width = window.innerWidth;
              canvas.width = width;
          });
          function animate() {
              if(animateHeader) {
                  ctx.clearRect(0,0,width,height);
                  for(var i in circles) {
                      circles[i].draw();
                  }
              }
              requestAnimationFrame(animate);
          }
          function Circle() {
              var _this = this;

              (function() {
                  _this.pos = {};
                  init();
              })();

              function init() {
                  _this.pos.x = Math.random()*width;
                  _this.pos.y = height+Math.random()*100;
                  _this.alpha = 0.1+Math.random()*0.3;
                  _this.scale = 0.1+Math.random()*0.3;
                  _this.velocity = Math.random();
              }

              this.draw = function() {
                  if(_this.alpha <= 0) {
                      init();
                  }

                  _this.pos.x -=0.1;
                  _this.pos.y -= _this.velocity;
                  _this.alpha -= 0.0005;
                  ctx.beginPath();
                  ctx.arc(_this.pos.x, _this.pos.y, _this.scale*10, 0, 2 * Math.PI, false);
                  ctx.fillStyle = 'rgba(255,255,255,'+ _this.alpha+')';
                  ctx.fill();
              };
          }
      })();
    }})

app/views/users/update.js.erb
<% if @user.errors.empty? %>
  Turbolinks.visit('<%= user_path(@user) %>');
<% else %>
  $('#user-edit-errors').html("<%= j render 'shared/error_messages', object: @user %>")
  $('#error_explanation').transition('tada');
<% end %>